### ISSUE TITLE
Add support for Configuration.Builder.setProxy(..)

### ISSUE THREAD

**Issue by menjoo** [DataDog/dd-sdk-kotlin-multiplatform#111]
### Feature description

Currently there is no support to configure Configuration.Builder.setProxy(.., ..)

**Comment by 0xnm** [comment]
Hi @menjoo! It is indeed on the list of the features we need to add to have a parity with iOS and Android SDKs.

Can you please help us to estimate the priority: is this a blocker for you? Are you currently already using our iOS and Android SDKs and looking forward to migrate to KMP SDK?

**Comment by menjoo** [comment]
> Hi [@menjoo](https://github.com/menjoo)! It is indeed on the list of the features we need to add to have a parity with iOS and Android SDKs.
> 
> Can you please help us to estimate the priority: is this a blocker for you? Are you currently already using our iOS and Android SDKs and looking forward to migrate to KMP SDK?

Hi @0xnm 
It is indeed a block to use the KMP SDK for us. Hope it can be added soon, otherwise we have to work with the 2 native SDK's and later migrate to the KMP SDK...

**Comment by menjoo** [comment]
To be more specific, I mean we need to set the LogsConfiguration.Builder.useCustomEndpoint so the traffic goes through our server proxy and then to DataDog cloud. Perhaps it is confusing that I used the word proxy. As that could also be referring to setting up the sdk to use a proxy within its network to access the internet in the first place.

**Comment by 0xnm** [comment]
Do you intend to modify the traffic?

We usually suggest using only proxy, because in this case traffic stays as it is, while `useCustomEndpoint` is something that we indeed have in the API, but its usage is highly discouraged (and maybe we will remove it in the future), because we already had few cases of the wrong implementation of such custom endpoint on the customer side, leading to the incorrect work of SDK or ingestion process.

**Comment by menjoo** [comment]
No we do not intent to modify the traffic. 

Our use case is that our app runs in our customers business. They have a firewall in their network so any traffic to a DataDog server could be blocked. Their firewall only opens up to our server. 

So what we need is tell the DataDog SDK to route the traffic through our server, which will forward everything to the DataDog server.

Is `Configuration.Builder.setProxy(.., ..)` right for this? or is `LogsConfiguration.Builder.useCustomEndpoint(..)` intended for this use case?

Also we want to do this for Logs and for RUM.

**Comment by 0xnm** [comment]
This is exact use-case for the proxy API indeed, no need for the `useCustomEndpoint`.

And yes, since it will be set up in the core SDK configuration, this setting will be used by all features.

**Comment by 0xnm** [comment]
This feature was released as a part of version [0.4.0](https://github.com/DataDog/dd-sdk-kotlin-multiplatform/releases/tag/0.4.0).
